### ISSUE TITLE
Custom HtmlAttributes

### ISSUE THREAD

**Issue by Haroenv** [AndrewFreemantle/Gravatar-HtmlHelper#4]
Hey! Thanks for your code, it's working swimmingly. I was just wondering if you knew a way of enabling custom attributes (and class) like you can usually do in html helpers, à la `new { @class = "img-responsive"}` as the last parameter. 

have a nice day 😄

**Comment by AndrewFreemantle** [comment]
That's a nice suggestion, thank you Haroen  😃 

If you always want a different class on the resulting Gravatar `<img>` tag (such as `img-responsive`), then I'd recommend editing your version to suit:

* GravatarHtmlHelper_Net35.cs - **line 227**
* GravatarHtmlHelper_Net40.cs - **line 106**
* GravatarHtmlHelper_NetCore.cs - **line 105**

Changing `"gravatar"` in the statement:
```
imgTag.Attributes.Add("class", "gravatar");
```
to the class name (or names) you need, e.g.
```
imgTag.Attributes.Add("class", "img-responsive some-other-class");
```

That'll tide you (and anyone else who needs the same) over until I've found some time to update the repository. Thanks again!

**Comment by Haroenv** [comment]
Yep, that was the same solution I'm using now too, but that means that I am not able to get this from NuGet since I needed to edit the code manually.

I tried adding a new parameter for the htmlAttributes, but that didn't work out (something about not being able to create a default for an object) so I did it the "fast" way 😄
